version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "installing something"

  pre_build:
    commands:
      - echo "we are in the pre build phase"

  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - mkdir -p test-reports
      - |
        if grep -Fq "Congratulations" index.html; then
          echo "Test passed"
          cat > test-reports/junit.xml <<'XML'
          <?xml version="1.0" encoding="UTF-8"?>
          <testsuites>
            <testsuite name="simple-check" tests="1" failures="0" errors="0" time="0.0">
              <testcase classname="index-check" name="contains-Congratulations" time="0.0"/>
            </testsuite>
          </testsuites>
          XML
                  else
                    echo "Test failed"
                    cat > test-reports/junit.xml <<'XML'
          <?xml version="1.0" encoding="UTF-8"?>
          <testsuites>
            <testsuite name="simple-check" tests="1" failures="1" errors="0" time="0.0">
              <testcase classname="index-check" name="contains-Congratulations" time="0.0">
                <failure message="String 'Congratulations' not found in index.html"/>
              </testcase>
            </testsuite>
          </testsuites>
          XML
          exit 1
        fi

  post_build:
    commands:
      - echo "we are in the post build phase"

reports:
  my-repo-group:                 
    files:
      - "**/*.xml"               
    base-directory: "test-reports"
    discard-paths: true
